### Run the below for installing the packages and using it
- Remove the hashes to run

In [1]:
# pip install numpy==1.22.4
# pip install pandas==1.5.3
# pip install scikit-learn==1.2.2
# pip install keras==2.12.0
# pip install tensorflow==2.12.0

### Import Packages

In [2]:
import pandas as pd
import numpy as np
import os



### Load Dataset
- Give the appropriate file path to load the data

In [3]:
data = pd.read_excel("C:\\Users\\DELL\Downloads\\harshita explo1.xlsx") # change the path to the excel file as per your filesystem

In [4]:
data.head()

Unnamed: 0  Laser power(W)  Traverse feed(mm/s)  Hatch Spacing(μm)  \
0           1             240                  500              200.0   
1           2             240                  500              200.0   
2           3             960                 1100              200.0   
3           4             960                 1100              200.0   
4           5             380                 1000              100.0   

   Layer thickness(μm)  Build direction  Yield strength (MPa)  \
0                   50                0                 245.0   
1                   50               90                 220.0   
2                   50                0                 232.0   
3                   50               90                 204.0   
4                   30                0                 280.0   

   Ultimate tensile strength (MPa)  Total elongation (%)  
0                            420.0                   5.9  
1                            400.0                   3.2  
2                            415.0                   8.0  
3                            437.0                   5.5  
4                            472.0                   7.8

In [5]:
data = data.iloc[:,1:]

In [6]:
data.head()

Laser power(W)  Traverse feed(mm/s)  Hatch Spacing(μm)  \
0             240                  500              200.0   
1             240                  500              200.0   
2             960                 1100              200.0   
3             960                 1100              200.0   
4             380                 1000              100.0   

   Layer thickness(μm)  Build direction  Yield strength (MPa)  \
0                   50                0                 245.0   
1                   50               90                 220.0   
2                   50                0                 232.0   
3                   50               90                 204.0   
4                   30                0                 280.0   

   Ultimate tensile strength (MPa)  Total elongation (%)  
0                            420.0                   5.9  
1                            400.0                   3.2  
2                            415.0                   8.0  
3                            437.0                   5.5  
4                            472.0                   7.8

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 8 columns):
 #   Column                           Non-Null Count  Dtype  
---  ------                           --------------  -----  
 0   Laser power(W)                   52 non-null     int64  
 1   Traverse feed(mm/s)              52 non-null     int64  
 2   Hatch Spacing(μm)                52 non-null     float64
 3   Layer thickness(μm)              52 non-null     int64  
 4   Build direction                  52 non-null     int64  
 5   Yield strength (MPa)             52 non-null     float64
 6   Ultimate tensile strength (MPa)  52 non-null     float64
 7   Total elongation (%)             52 non-null     float64
dtypes: float64(4), int64(4)
memory usage: 3.4 KB


# Modeling

In [8]:
X = data[['Laser power(W)','Traverse feed(mm/s)','Hatch Spacing(μm)','Layer thickness(μm)','Build direction']]
y = data[['Yield strength (MPa)','Ultimate tensile strength (MPa)','Total elongation (%)']]

### Linear Regression

In [9]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [10]:
LR_model = LinearRegression()

In [11]:
LR_model.fit(X,y)

LinearRegression()

In [12]:
predictions = LR_model.predict(X)

In [13]:
predictions

array([[247.37607831, 364.1675412 ,   6.21915909],
       [225.3076385 , 356.70612613,   4.52918943],
       [230.99570759, 445.26115208,   9.41833675],
       [208.92726779, 437.79973701,   7.72836709],
       [263.22043511, 426.77064174,   7.26481269],
       [241.15199531, 419.30922667,   5.57484303],
       [233.76356701, 362.80664557,   7.27722623],
       [211.6951272 , 355.34523051,   5.58725657],
       [256.71619894, 429.56033113,   7.27871278],
       [234.64775914, 422.09891607,   5.58874312],
       [254.94204967, 427.3908241 ,   7.39920688],
       [232.87360987, 419.92940903,   5.70923722],
       [255.83895829, 426.07988299,   7.2886091 ],
       [233.77051848, 418.61846793,   5.59863944],
       [255.3086803 , 424.94989196,   7.31468718],
       [233.2402405 , 417.48847689,   5.62471752],
       [261.81291647, 422.16020256,   7.30078709],
       [239.74447667, 414.6987875 ,   5.61081744],
       [258.15549543, 416.69419826,   7.31217405],
       [236.08705563, 409.23278

In [14]:
LR_mse = mean_squared_error(y,predictions)

In [15]:
LR_rmse = np.sqrt(LR_mse)

In [16]:
print("Mean Squared Error (MSE) = ",LR_mse)
print("Root Mean Squared Error (RMSE) = ",LR_rmse)

Mean Squared Error (MSE) =  1123.0615194510735
Root Mean Squared Error (RMSE) =  33.51211004176063


### KNeighbors Regression

In [17]:
from sklearn.neighbors import KNeighborsRegressor


In [18]:
KNN_model = KNeighborsRegressor()
# fit model
KNN_model.fit(X, y)

KNeighborsRegressor()

In [19]:
KNN_predictions = KNN_model.predict(X)

In [20]:
KNN_predictions

array([[250.4 , 380.  ,   4.5 ],
       [246.8 , 383.8 ,   4.18],
       [227.52, 401.04,   7.24],
       [225.28, 397.48,   7.06],
       [247.92, 404.44,   6.14],
       [231.08, 363.68,   4.72],
       [222.18, 357.74,   7.26],
       [224.74, 357.58,   6.38],
       [245.78, 371.94,   6.4 ],
       [218.94, 331.78,   4.54],
       [243.8 , 394.8 ,   9.48],
       [222.2 , 405.8 ,   6.96],
       [248.4 , 446.4 ,   8.62],
       [232.6 , 454.2 ,   7.26],
       [243.8 , 394.8 ,   9.48],
       [222.2 , 405.8 ,   6.96],
       [259.8 , 400.4 ,   8.8 ],
       [247.  , 408.8 ,   6.48],
       [268.2 , 435.8 ,   4.98],
       [265.2 , 436.8 ,   4.56],
       [231.78, 321.74,   4.9 ],
       [234.34, 321.58,   4.02],
       [243.8 , 394.8 ,   9.48],
       [222.2 , 405.8 ,   6.96],
       [264.6 , 413.4 ,   9.6 ],
       [232.4 , 412.8 ,   6.64],
       [243.8 , 394.8 ,   9.48],
       [222.2 , 405.8 ,   6.96],
       [218.38, 343.94,   6.18],
       [220.94, 343.78,   5.3 ],
       [23

In [21]:
KNN_mse = mean_squared_error(y,KNN_predictions)
KNN_rmse = np.sqrt(KNN_mse)

In [22]:
print("Mean Squared Error (MSE) = ",KNN_mse)
print("Root Mean Squared Error (RMSE) = ",KNN_rmse)

Mean Squared Error (MSE) =  1188.3519076923073
Root Mean Squared Error (RMSE) =  34.47248044008884


### Decision Tree Regression

In [23]:
from sklearn.tree import DecisionTreeRegressor

In [24]:

DT_model = DecisionTreeRegressor()
DT_model.fit(X, y)

DT_predictions = DT_model.predict(X)
DT_predictions

array([[2.450e+02, 4.200e+02, 5.900e+00],
       [2.200e+02, 4.000e+02, 3.200e+00],
       [2.320e+02, 4.150e+02, 8.000e+00],
       [2.040e+02, 4.370e+02, 5.500e+00],
       [2.800e+02, 4.720e+02, 7.800e+00],
       [2.300e+02, 4.750e+02, 5.600e+00],
       [2.470e+02, 4.250e+02, 9.400e+00],
       [2.220e+02, 4.000e+02, 5.700e+00],
       [1.900e+02, 3.230e+02, 6.700e+00],
       [2.140e+02, 3.400e+02, 3.200e+00],
       [2.870e+02, 4.750e+02, 1.090e+01],
       [2.450e+02, 4.700e+02, 9.400e+00],
       [2.380e+02, 4.640e+02, 1.010e+01],
       [2.280e+02, 4.780e+02, 7.000e+00],
       [2.640e+02, 4.510e+02, 8.600e+00],
       [2.470e+02, 4.820e+02, 6.500e+00],
       [3.180e+02, 4.500e+02, 8.600e+00],
       [2.630e+02, 4.100e+02, 6.900e+00],
       [2.700e+02, 4.500e+02, 6.600e+00],
       [2.600e+02, 4.600e+02, 5.200e+00],
       [3.070e+02, 4.240e+02, 3.000e+00],
       [2.100e+02, 2.210e+02, 3.000e-01],
       [2.480e+02, 3.860e+02, 8.600e+00],
       [2.280e+02, 4.120e+02, 7.00

In [25]:
DT_mse = mean_squared_error(y,DT_predictions)
DT_rmse = np.sqrt(DT_mse)

In [26]:
print("Mean Squared Error (MSE) = ",DT_mse)
print("Root Mean Squared Error (RMSE) = ",DT_rmse)

Mean Squared Error (MSE) =  0.0
Root Mean Squared Error (RMSE) =  0.0


#### This is an overfitted model

### Random Forest Regression

In [27]:
from sklearn.ensemble import RandomForestRegressor

In [28]:

RF_model = RandomForestRegressor()
RF_model.fit(X, y)

RF_predictions = RF_model.predict(X)
RF_predictions

array([[247.766 , 410.162 ,   5.485 ],
       [222.404 , 385.054 ,   3.625 ],
       [230.48  , 417.41  ,   7.501 ],
       [209.844 , 421.354 ,   5.33  ],
       [267.02  , 456.81  ,   7.606 ],
       [237.05  , 456.84  ,   6.212 ],
       [241.67  , 413.17  ,   8.284 ],
       [220.208 , 393.122 ,   5.511 ],
       [213.52  , 364.07  ,   6.907 ],
       [213.214 , 362.964 ,   4.679 ],
       [269.93  , 456.37  ,   9.787 ],
       [246.11  , 455.48  ,   8.792 ],
       [245.2   , 455.96  ,   9.26  ],
       [231.21  , 470.43  ,   7.137 ],
       [259.57  , 451.72  ,   8.689 ],
       [246.43  , 468.01  ,   6.93  ],
       [298.84  , 440.52  ,   8.136 ],
       [263.83  , 425.56  ,   6.754 ],
       [269.22  , 444.3   ,   6.28  ],
       [258.39  , 449.02  ,   4.9094],
       [273.31  , 371.2   ,   2.932 ],
       [226.96  , 309.04  ,   2.163 ],
       [247.47  , 401.27  ,   8.294 ],
       [233.71  , 415.14  ,   7.045 ],
       [268.99  , 427.65  ,   7.469 ],
       [241.84  , 429.51 

In [29]:
RF_mse = mean_squared_error(y,RF_predictions)
RF_rmse = np.sqrt(RF_mse)

In [30]:
print("Mean Squared Error (MSE) = ",RF_mse)
print("Root Mean Squared Error (RMSE) = ",RF_rmse)

Mean Squared Error (MSE) =  168.02329514666675
Root Mean Squared Error (RMSE) =  12.962379995458656


### Cross Validation

In [31]:
# evaluate multioutput regression model with k-fold cross-validation
from numpy import absolute,mean,std
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedKFold

In [32]:
rf_model = RandomForestRegressor()
cv = RepeatedKFold(n_splits=10, n_repeats=3, random_state=1)

n_scores = cross_val_score(rf_model, X, y, scoring='neg_mean_absolute_error', cv=cv, n_jobs=-1)
n_scores = absolute(n_scores)
# summarize performance
print('MAE: %.3f (%.3f)' % (mean(n_scores), std(n_scores)))

MAE: 19.805 (6.293)


### Grid Search

In [33]:
from sklearn.model_selection import GridSearchCV,train_test_split

In [34]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.05,random_state=0)

In [35]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((49, 5), (3, 5), (49, 3), (3, 3))

In [36]:
parameters = {
    'n_estimators': [99,100,125,130,135,140,145,149,150,155,160,165,170,199,200,249,250,299,300],
    'max_depth': [4,6,7,8,9,15,19,21,25,30,35,40],
}
regr = RandomForestRegressor(random_state=0)

clf = GridSearchCV(regr, parameters)
clf.fit(X_train, y_train)

GridSearchCV(estimator=RandomForestRegressor(random_state=0),
             param_grid={'max_depth': [4, 6, 7, 8, 9, 15, 19, 21, 25, 30, 35,
                                       40],
                         'n_estimators': [99, 100, 125, 130, 135, 140, 145, 149,
                                          150, 155, 160, 165, 170, 199, 200,
                                          249, 250, 299, 300]})

In [ ]:
clf.best_params_

In [ ]:
train_predictions = clf.predict(X_train)
test_predictions = clf.predict(X_test)

In [ ]:
train_mse = mean_squared_error(y_train,train_predictions)
test_mse = mean_squared_error(y_test,test_predictions)

train_rmse = np.sqrt(train_mse)
test_rmse = np.sqrt(test_mse)

In [ ]:
train_mse,train_rmse, test_mse,test_rmse

In [ ]:
print("Train - Mean Squared Error (MSE) = ",train_mse)
print("Train - Root Mean Squared Error (RMSE) = ",train_rmse)

print("Test - Mean Squared Error (MSE) = ",test_mse)
print("Test - Root Mean Squared Error (RMSE) = ",test_rmse)

### Random Forest is the best model so far with test rmse of 23

### Keras Models

In [288]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LeakyReLU
model = Sequential()
model.add(Dense(25, input_dim=5, kernel_initializer='he_uniform', activation='relu'))
model.add(Dense(32, kernel_initializer='he_uniform', activation=LeakyReLU(alpha=0.01)))
model.add(Dense(64, kernel_initializer='he_uniform', activation=LeakyReLU(alpha=0.01)))
model.add(Dense(128, kernel_initializer='he_uniform', activation=LeakyReLU(alpha=0.01)))
model.add(Dense(256, kernel_initializer='he_uniform', activation=LeakyReLU(alpha=0.01)))
model.add(Dense(512, kernel_initializer='he_uniform', activation=LeakyReLU(alpha=0.01)))
model.add(Dense(512, kernel_initializer='he_uniform', activation=LeakyReLU(alpha=0.01)))
model.add(Dense(512, kernel_initializer='he_uniform', activation=LeakyReLU(alpha=0.01)))
model.add(Dense(512, kernel_initializer='he_uniform', activation=LeakyReLU(alpha=0.01)))

model.add(Dense(512, kernel_initializer='he_uniform', activation=LeakyReLU(alpha=0.01)))
model.add(Dense(512, kernel_initializer='he_uniform', activation=LeakyReLU(alpha=0.01)))
model.add(Dense(512, kernel_initializer='he_uniform', activation=LeakyReLU(alpha=0.01)))
model.add(Dense(512, kernel_initializer='he_uniform', activation=LeakyReLU(alpha=0.01)))
model.add(Dense(512, kernel_initializer='he_uniform', activation=LeakyReLU(alpha=0.01)))
model.add(Dense(256, kernel_initializer='he_uniform', activation="relu"))
model.add(Dense(256, kernel_initializer='he_uniform', activation="relu"))
model.add(Dense(128, kernel_initializer='he_uniform', activation="relu"))
model.add(Dense(64, kernel_initializer='he_uniform', activation="relu"))
model.add(Dense(3))

In [289]:
model.compile(loss ='mse', optimizer = 'adam')
model.summary()
history = model.fit(X_train, y_train, verbose = 'auto',epochs = 400)
# from sklearn.metrics import mean_absolute_error

Model: "sequential_33"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_490 (Dense)           (None, 25)                150       
                                                                 
 dense_491 (Dense)           (None, 32)                832       
                                                                 
 dense_492 (Dense)           (None, 64)                2112      
                                                                 
 dense_493 (Dense)           (None, 128)               8320      
                                                                 
 dense_494 (Dense)           (None, 256)               33024     
                                                                 
 dense_495 (Dense)           (None, 512)               131584    
                                                                 
 dense_496 (Dense)           (None, 512)             

In [290]:
y_pred = model.predict(X_test)

1/1 [==============================] - 0s 182ms/step


In [291]:
mse = mean_squared_error(y_test,y_pred)
rmse = np.sqrt(mse)

In [292]:
print("Mean Squared Error (MSE) = ",mse)
print("Root Mean Squared Error (RMSE) = ",rmse)

(14663.022919522171, 121.09096960352647)